info:
  version: 1.0.0-SNAPSHOT
  name: gateway
  artifact-id: ${spring.application.name}
  group-id: com.github.dactiv.service

healthan:
  authentication:
    spring:
      security:
        enabled: false