dactiv:
  captcha:
    tianai:
      api-base-url: http://localhost:8080/resource
      template-map:
        ROTATE:
          - tag: default
            active-image:
              type: classpath
              data: tianai/template/rotate/1/active.png
            fixed-image:
              type: classpath
              data: tianai/template/rotate/1/fixed.png
        SLIDER:
          - tag: default
            active-image:
              type: classpath
              data: tianai/template/slider/1/active.png
            fixed-image:
              type: classpath
              data: tianai/template/slider/1/fixed.png
          - tag: default
            active-image:
              type: classpath
              data: tianai/template/slider/2/active.png
            fixed-image:
              type: classpath
              data: tianai/template/slider/2/fixed.png
      resource-map:
        SLIDER:
          - type: classpath
            data: tianai/1.jpg
            tag: default
          - type: classpath
            data: tianai/2.jpg
            tag: default
          - type: classpath
            data: tianai/3.jpg
            tag: default
          - type: classpath
            data: tianai/4.jpg
            tag: default
          - type: classpath
            data: tianai/4.jpg
            tag: default
          - type: classpath
            data: tianai/5.jpg
            tag: default
          - type: classpath
            data: tianai/6.jpg
            tag: default
          - type: classpath
            data: tianai/7.jpg
            tag: default
          - type: classpath
            data: tianai/8.jpg
            tag: default
          - type: classpath
            data: tianai/9.jpg
            tag: default
          - type: classpath
            data: tianai/10.jpg
            tag: default
        ROTATE:
          - type: classpath
            data: tianai/1.jpg
            tag: default
          - type: classpath
            data: tianai/2.jpg
            tag: default
          - type: classpath
            data: tianai/3.jpg
            tag: default
          - type: classpath
            data: tianai/4.jpg
            tag: default
          - type: classpath
            data: tianai/4.jpg
            tag: default
          - type: classpath
            data: tianai/5.jpg
            tag: default
          - type: classpath
            data: tianai/6.jpg
            tag: default
          - type: classpath
            data: tianai/7.jpg
            tag: default
          - type: classpath
            data: tianai/8.jpg
            tag: default
          - type: classpath
            data: tianai/9.jpg
            tag: default
          - type: classpath
            data: tianai/10.jpg
            tag: default
        CONCAT:
          - type: classpath
            data: tianai/1.jpg
            tag: default
          - type: classpath
            data: tianai/2.jpg
            tag: default
          - type: classpath
            data: tianai/3.jpg
            tag: default
          - type: classpath
            data: tianai/4.jpg
            tag: default
          - type: classpath
            data: tianai/4.jpg
            tag: default
          - type: classpath
            data: tianai/5.jpg
            tag: default
          - type: classpath
            data: tianai/6.jpg
            tag: default
          - type: classpath
            data: tianai/7.jpg
            tag: default
          - type: classpath
            data: tianai/8.jpg
            tag: default
          - type: classpath
            data: tianai/9.jpg
            tag: default
          - type: classpath
            data: tianai/10.jpg
            tag: default
  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: 19880602
    auto-delete:
      expiration:
        - bucket-name: "dactiv.service.resource.temp"
          expiration-time:
            value: 30
            unity: DAYS
  service-portal:
    resource:
      # 如果发送邮箱或短信不需要行为验证码，将一下配置开启
      #captcha:
      #  sms:
      #    interceptor-type: ''
      #  email:
      #    interceptor-type: ''

spring:
  elasticsearch:
    uris: http://localhost:9200
  data:
    redis:
      host: localhost
      port: 6379
      password: 
  datasource:
    url: jdbc:mysql://localhost:3306/dactiv_resource?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    type: com.zaxxer.hikari.HikariDataSource
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
    virtual-host: /
    # 开启发送失败返回
    publisher-returns: true
    # 开启发送确认
    publisher-confirm-type: correlated
    listener:
      # 开启 ack
      simple:
        acknowledge-mode: manual
        concurrency: 8
        retry:
          # 重试初始间隔时间
          initial-interval: 2000
          # 间隔时间乘子，间隔时间 * 乘子 = 下一次的间隔时间，最大不能超过设置的最大间隔时间
          multiplier: 2
          # 启用重试
          enabled: true
      # 开启 ack
      direct:
        acknowledge-mode: manual
        retry:
          # 重试初始间隔时间
          initial-interval: 2000
          # 间隔时间乘子，间隔时间 * 乘子 = 下一次的间隔时间，最大不能超过设置的最大间隔时间
          multiplier: 2
          # 启用重试
          enabled: true
    # 支持消息的确认与返回
    template:
      mandatory: true